env:
  LATEST_FILE: production_sophia_LATEST
  SRC_BUCKET: sophia-db-backup
  DST_BUCKET: sophia-dumps-without-pii
  DB_USER: sophia_remove_pii
  DB_NAME: sophia_remove_pii
  DB_HOST: db-testing.czadkgtmhhky.us-east-1.rds.amazonaws.com
  RAILS_ENV: test
# cronjob common settings
namespace: bitbucket
serviceAccount:
  role: arn:aws:iam::773369453641:role/sophia-remove-pii
schedule: "0 9 * * *"
successfulJobsHistoryLimit: 0
failedJobsHistoryLimit: 0
restartPolicy: OnFailure
containers:
  name: finalizer
  image: busybox
  pullPolicy: IfNotPresent
initContainers:
  # init containers common settings
  images:
  - name: psql
    container: 773369453641.dkr.ecr.us-east-1.amazonaws.com/remove-pii:latest
  - name: rails
    container: 773369453641.dkr.ecr.us-east-1.amazonaws.com/sophia:latest
  pullPolicy: Always
  # init containers definition
  definitions:
  # load db dump
  - name: loadDbDump
    command: ./load-db-dump.sh
    volumeMounts:
    - name: dumps
      path: /mnt/dumps
    - name: job
      path: /tmp/job
  # remove pii
  - name: removePii
    command: /tmp/script/remove-pii.sh
    volumeMounts:
    - name: job 
      path: /tmp/job
    - name: db-config
      path: /home/sophia/sophia/config/database.yml
      subPath: database.yml
    - name: scripts
      path: /tmp/scripts/remove-pii.sh
      subPath: remove-pii.sh
  # upload dump without pii
  - name: uploadDumpWithoutPii
    command: ./upload-dump-without-pii.sh
    volumeMounts:
    - name: dumps
      path: /mnt/dumps
    - name: job
      path: /tmp/job
  # prepare dev dataset
  - name: prepareDevDataset
    command: /tmp/script/prepare-dev-dataset.sh
    volumeMounts:
    - name: job 
      path: /tmp/job
    - name: db-config
      path: /home/sophia/sophia/config/database.yml
      subPath: database.yml
    - name: scripts
      path: /tmp/scripts/prepare-dev-dataset.sh
      subPath: prepare-dev-dataset.sh
  # upload dev dump
  - name: uploadDevDump
    command: ./upload-dev-dump.sh
    volumeMounts:
    - name: dumps
      path: /mnt/dumps
    - name: job
      path: /tmp/job