apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.db_user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.db_password | b64enc }}
