apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val }}
{{- end}}
{{ (.Files.Glob "config/database.yml").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}