---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role}}
  name: {{ .Chart.Name }}
  namespace: {{ template "chart.namespace" . }}
