apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-nginx
data:
  default.conf: |-
    server {
        listen 80 default_server;
        root /var/www/html/public;
        server_name  _;
        index index.php;

        client_max_body_size 100M;
        
        location / {
            try_files $uri $uri/ /index.php?$args;
        }
        
        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param HTTP_X_REQUEST_START "t=${msec}";
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 300;
        }
    }
