# Default values for cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterName: ""
replicaCount: 1

image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  pullPolicy: Always
  # tag: "v1.21.2"
  tag: "v1.23.1"

nameOverride: ""
fullnameOverride: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi

labels:
  common:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  deployment:
    app: cluster-autoscaler

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether a service account should be created
  create: true
  clusterScoped: true
