apiVersion: v1
kind: Service
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
{{ include "newrelic-php-agent.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
